# Generated by Django 6.0.4 on 2026-04-22 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('gender', models.CharField(db_index=True, max_length=20)),
                ('gender_probability', models.FloatField()),
                ('age', models.IntegerField(db_index=True)),
                ('age_group', models.CharField(db_index=True, max_length=20)),
                ('country_id', models.CharField(db_index=True, max_length=2)),
                ('country_name', models.CharField(max_length=100)),
                ('country_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gender'], name='profiles_pr_gender_fc2e15_idx'), models.Index(fields=['age_group'], name='profiles_pr_age_gro_c64938_idx'), models.Index(fields=['country_id'], name='profiles_pr_country_dcd88d_idx'), models.Index(fields=['age'], name='profiles_pr_age_e41ac9_idx'), models.Index(fields=['gender_probability'], name='profiles_pr_gender__f55b6d_idx'), models.Index(fields=['country_probability'], name='profiles_pr_country_60e12a_idx')],
            },
        ),
    ]
